export class Focus {
    kode_spg: string; 
    nama_spg: string; 
    nama_toko: string; 
    depot: string;
    VPRO_PPRO_MATEX_KIMEX: string;
    BODELAC_2IN1_ANTI_KARAT_RM: string;
    F_5100: string;
    F_5200: string;
    F_5400: string;
    PLATONE_800_or_BEE_BRAND_1000: string;
    FLAWLESS_BW: string;
    WEATHERBOND_RM: string;
    MATEX_CAT_GENTENG_CCM: string;
    STONESHIELD: string;
    WEATHERBOND_BW: string;
    NIPPON_WOOD_STAIN_RM: string;
    ELASTEX_RM: string;
    TIMBERFINISH_RM: string;
    SPOTLESS_BW: string;
    NP_ZINC_CHROMATE_GREEN: string;
    BODELAC_2IN1_ANTI_KARAT_CCM: string;
    ROOF_COATING_RM: string;
    NIPPON_9000: string;
    SPORTSKOTE_CCM: string;
    NIPPON_WOOD_STAIN_CCM: string;
    ELASTEX_TINTING: string;
    BODELAC_8000_ZINC_CHROMATE_GREEN: string;
}
